name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build with Buildozer
      uses: pythonforandroid/python-for-android-ci@main
      with:
        command: |
          buildozer android debug
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
