name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          zip \
          unzip \
          ccache \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev

    - name: Install buildozer
      run: |
        pip install --upgrade pip
        pip install --upgrade buildozer
        pip install --upgrade cython

    - name: Build with buildozer
      run: |
        buildozer android debug
      env:
        GRADLE_OPTS: "-Xmx4096m"

    - name: List bin directory
      if: always()
      run: |
        echo "Contents of bin directory:"
        ls -la bin/ || echo "No bin directory found"

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: bible-text-converter-apk
        path: bin/*.apk
        if-no-files-found: error
